triggers/urls.py
from django.conf.urls import url
from . import views
from zbtrigger import settings
# from zbtrigger.settings import STATICFILES_DIRS
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login/$', views.login_view, name='login_view'),
    url(r'^logout/$', views.logout_view, name='logout_view'),
    url(r'^netmanager/file_view/$', views.file_view, name='file_view'),

    url(r'^parameter_init/$', views.parameter_init, name='parameter_init'),
    url(r'^item_init/$', views.item_init, name='item_init'),
    url(r'^internet_lastvalue/$', views.internet_lastvalue, name='internet_lastvalue'),
    url(r'^zhuanxian_lastvalue/$', views.zhuanxian_lastvalue, name='zhuanxian_lastvalue'),
    url(r'^zhuanxian_status/$', views.zhuanxian_status, name='zhuanxian_status'),
    url(r'^device_value/$', views.device_value, name='device_value'),
    url(r'^video_status/$', views.video_status, name='video_status'),
    url(r'^video/$', views.video, name='video'),
    url(r'^line_history/(?P<item_description>.+)/$', views.line_history, name='line_history'),
    url(r'^line_status/(?P<item_description>.+)/$', views.line_status, name='line_status'),
    url(r'^host_list/(?P<server_name>.+)/$', views.host_list, name='host_list'),
    url(r'^zhuanxian_detail/(?P<name>.+)/$', views.zhuanxian_detail, name='zhuanxian_detail'),
    url(r'^trigger_list/(?P<server>.+)/$', views.trigger_list, name='trigger_list'),
    url(r'^backup/$', views.backup_netdevice, name='backup_netdevice'),
    url(r'^audit/$', views.fileaudit, name='fileaudit'),
    url(r'^netmanager/$', views.netmanager, name='netmanager'),
    url(r'^netmanager_status/$', views.netmanager_status, name='netmanager_status'),
    url(r'^file_status/$', views.file_change_status, name='file_change_status'),
    url(r'^ftp_status/$', views.ftp_status, name='ftp_status'),
    # url(r'^netmanager/(?P<device_name>.+)/$', views.fileaudit, name='fileaudit'),
    url(r'^netmanager/(?P<device_name>.+)/$', views.file_content, name='file_content'),
    url(r'^error/$', views.login_error, name='login_error'),

    # test url
    url(r'^compare/$', views.compare, name='compare'),
    url(r'^ajax/$', views.ajax, name='ajax'),
    url(r'^add/(?P<a>(\d+))/(?P<b>(\d+))/$', views.add, name='add'),
    url(r'^add1/$', views.add1, name='add1'),
    url(r'^ajax_list/$', views.ajax_list, name='ajax_list'),
    url(r'^ajax_dict/$', views.ajax_dict, name='ajax_dict'),
    url(r'^web/$', views.getweb, name='getweb'),
]

zbtrigger/urls.py
from django.conf.urls import include, url
from django.contrib import admin
#from django.contrib.auth import views as auth_views
urlpatterns = [
    url(r'^trigger/', include('triggers.urls', namespace="triggers")),
    url(r'^admin/', include(admin.site.urls)),
    #url(r'^admin/login/$', auth_views.login),

]

triggers/views.py
# coding=utf-8
from __future__ import unicode_literals
from django.contrib.auth import authenticate, login, logout, user_login_failed
from django.contrib.auth.decorators import login_required, permission_required
from django.shortcuts import render, render_to_response, HttpResponseRedirect, redirect
from django.template import RequestContext
from triggers.models import Hosts, Parameters, TriggerWarrning, ZhuanXian, Video, Item, ItemLastValue, History, \
    InitPara, NetDevices, FtpServer
from zbtrigger.settings import BASE_DIR
from filecmp import cmp
from datetime import *
from django.db import connection, transaction
from django.http import HttpResponse
from django.contrib.auth.models import User
import json
import urllib2
import time
import datetime
import threading
import os
import telnetlib
import ftplib
import sys
import pynetsnmp


# login
def login_view(request):
    username = request.POST.get('username')
    password = request.POST.get('password')
    print username, password
    user = authenticate(username=username, password=password)
    print user
    print request.path
    if user is not None:
        if user.is_active:
            login(request, user)
            return render(request, 'triggers/index.html')
            return red
        else:
            return render(request, 'triggers/error.html')
    else:
        return render(request, 'triggers/login.html')


# logout
def logout_view(request):
    logout(request)
    return render(request, 'triggers/logout.html')


def login_error(request):
    return render(request, 'triggers/error.html')


# 首页
@login_required(login_url='/trigger/login')
def index(request):
    return render(request, 'triggers/index.html')


# 通过zabbix server api 返回结果集（数组字典）
def request_zabbix(url, data, header_type, header_json):
    request_http = urllib2.Request(url, data)
    request_http.add_header(header_type, header_json)
    try:
        result_data = urllib2.urlopen(request_http)
        response_data = json.loads(result_data.read())
        result_data.close()
        if 'error' in response_data.keys():
            return ''
        else:
            return response_data['result']
    except urllib2.URLError, e:
        print url, e
        return ''


# 过滤参数的空格
def filter_space(*parameter):
    string = []
    for p in parameter:
        if p:
            p1 = str.strip(p.encode("utf-8"))
        else:
            p1 = ""
        string.append(p1)
    return string


# 第一步：手工添加的服务器参数初始化，获取authid
def parameter_init(request):
    p_server = Parameters.objects.all()
    server_status = []
    for parameter in p_server:
        data = json.dumps(
            dict(jsonrpc="2.0",
                 method="user.login",
                 params={
                     "user": parameter.user,
                     "password": parameter.password,
                 },
                 id=0
                 )
        )
        parameter.authid = request_zabbix(parameter.url, data, parameter.header_type, parameter.header_json)
        # print parameter.serverip, parameter.authid
        if parameter.authid != '':
            parameter.save()
            result1 = {
                'serverip': parameter.serverip,
                'status': u'成功',
            }
            server_status.append(result1)
        else:
            result2 = {
                'serverip': parameter.serverip,
                'status': u'失败',
            }
            server_status.append(result2)
    return render(request, 'triggers/parameter_init.html', {'server_status': server_status})


# 第二步：主机同步线程 后台每小时同步一次
def host_thread(request):
    start = time.time()
    p_server = Parameters.objects.all()
    # p_server = Parameters.objects.filter(company=u'北京总部')
    host1 = []
    Hosts.objects.all().delete()

    def request_thread(url, data_json, header_type, header_json, hostid, company, hostname, status):
        re = request_zabbix(url, data_json, header_type, header_json)
        if re:
            for r in re:
                req = {
                    "hostid": hostid,
                    "company": company,
                    "hostname": hostname,
                    "hostip": r['ip'],
                    "status": status
                }
                host1.append(req)

    for parameter in p_server:
        data = json.dumps(
            dict(jsonrpc="2.0",
                 method="host.get",
                 params={
                     "output": ["hostid", "name", "status"],
                     "filter": {"status": 0},
                 },
                 auth=parameter.authid,
                 id=1
                 )
        )
        host_zabbix = request_zabbix(parameter.url, data, parameter.header_type, parameter.header_json)
        t = []
        for host in host_zabbix:
            data_hostinterface = json.dumps(
                dict(jsonrpc="2.0",
                     method="hostinterface.get",
                     params={
                         "output": ["hostid", "ip"],
                         "hostids": {"hostid": host['hostid']},
                         "limit": 1
                     },
                     auth=parameter.authid,
                     id=1
                     )
            )
            t.append(threading.Thread(target=request_thread, args=(parameter.url,
                                                                   data_hostinterface,
                                                                   parameter.header_type,
                                                                   parameter.header_json,
                                                                   host['hostid'],
                                                                   parameter.company,
                                                                   host['name'],
                                                                   host['status']
                                                                   )))

        for j in range(len(t)):
            t[j].daemon = True
            t[j].start()

        for z in range(len(t)):
            t[z].join()

    for h in host1:
        # if not Hosts.objects.filter(hostip=h['hostip']):
        # print h['hostid'], h['hostip']
        h1 = Hosts(company=h['company'], hostid=h['hostid'], hostname=h['hostname'], hostip=h['hostip'],
                   status=h['status'])
        h1.save()
    end = time.time()
    print end - start
    # return render(request, 'triggers/host_init.html')


# 第三步：异常同步线程，后台每2分钟同步一次
def trigger_thread(request):
    start = time.time()
    TriggerWarrning.objects.all().delete()
    p_host = Hosts.objects.all()
    t = []
    trigger1 = []

    def request_thread(url, data, header_type, header_json, host_id, hostid, company, hostname, hostip):
        re = request_zabbix(url, data, header_type, header_json)
        if re:
            for r in re:
                req = {
                    "host_id": host_id,
                    "hostid": hostid,
                    "company": company,
                    "hostname": hostname,
                    "hostip": hostip,
                    "triggerid": r['triggerid'],
                    "lastchange": r['lastchange'],
                    "description": r['description']
                }
                trigger1.append(req)

    for host in p_host:
        parameter = Parameters.objects.get(company=host.company)
        data_trigger = json.dumps(
            dict(jsonrpc="2.0",
                 method="trigger.get",
                 params={
                     "output": ["triggerid", "description", "lastchange"],
                     "filter": {"value": 1, "status": 0},
                     "hostids": {"hostid": host.hostid},
                 },
                 auth=parameter.authid,
                 id=1
                 )
        )
        t.append(threading.Thread(target=request_thread, args=(parameter.url,
                                                               data_trigger,
                                                               parameter.header_type,
                                                               parameter.header_json,
                                                               host.id,
                                                               host.hostid,
                                                               host.company,
                                                               host.hostname,
                                                               host.hostip)))

    for j in range(len(t)):
        t[j].daemon = True
        t[j].start()

    for z in range(len(t)):
        t[z].join()

    for trigger in trigger1:
        timearray = time.localtime(float(trigger['lastchange']))
        trigger['lastchange'] = time.strftime("%Y-%m-%d %H:%M:%S", timearray)
        if not TriggerWarrning.objects.filter(hostip=trigger['hostip'], description=trigger['description']):
            t1 = TriggerWarrning(hosts_id=trigger['host_id'],
                                 company=trigger['company'],
                                 hostname=trigger['hostname'],
                                 hostip=trigger['hostip'],
                                 triggerid=trigger['triggerid'],
                                 hostid=trigger['hostid'],
                                 description=trigger['description'],
                                 lastchange=trigger['lastchange']
                                 )
            t1.save()
    end = time.time()
    print end - start
    # return render(request, 'triggers/trigger_init.html')


# 手动同步添加设备【主要是专线和互联网信息】的主机ID，获取hostid
def item_init(request):
    item_list = Item.objects.all()
    for item in item_list:
        item.hostid = Hosts.objects.get(hostip=item.hostip, company=item.company).hostid
        item.save()
    return render(request, 'triggers/item_init.html')


# 获取专线状态
def zhuanxian_status(request):
    # zhuanxian status

triggers/templates/triggers/ajax.html
<!DOCTYPE html>
<html lang="zh-CN">
{% load staticfiles %}
<head>
    <meta charset="UTF-8">
    <title></title>
    <script src="/static/bootstrap/js/jquery.min.js"></script>
    <script>
        function loadXMLDoc() {
            var xmlhttp;
            if (window.XMLHttpRequest) {// code for IE7+, Firefox, Chrome, Opera, Safari
                xmlhttp = new XMLHttpRequest();
            }
            else {// code for IE6, IE5
                xmlhttp = new ActiveXObject("Microsoft.XMLHTTP");
            }
            xmlhttp.onreadystatechange = function () {
                if (xmlhttp.readyState == 4 && xmlhttp.status == 200) {
                    document.getElementById("myDiv").innerHTML = xmlhttp.responseText;
                }
            };
            xmlhttp.open("GET", "/static/ajax/out1.txt", true);
            xmlhttp.send();
        }
    </script>
</head>
<body>
<div id="myDiv"><h2>使用 AJAX 修改该文本内容</h2></div>
<button type="button" onclick="loadXMLDoc()">修改内容</button>

<div id="myDiv2"><h2>输入两个数求和</h2></div>
<form>
    a: <input id="a"><br>
    b: <input id="b"><br>
    <button type="button" onclick="ajax_request()">求和</button>
    <div>结果：<span id="result"></span></div>
</form>
<div id="test1"></div>
<h3 id="test">请点击下面的按钮，通过 jQuery AJAX 改变这段文本。</h3>
<button id="btn1" type="button">获得外部的内容</button>

<p>请输入两个数字</p>

<form action="/trigger/add1/" method="get">
    a: <input type="text" id="a1" name="a1"> <br>
    b: <input type="text" id="b1" name="b1"> <br>

    <p>result: <span id='result1'></span></p>
    <button type="button" id='sum1'>提交</button>
</form>
<p>
    <button type="button" id="list">Ajax 加载列表</button>
</p>
<p id="list_result"></p>

<p>
    <button type="button" id="dict">Ajax 加载字典</button>
</p>
<p id="dict_result"></p>

<p>
    <button type="button" id="internet">互联网速度</button>
</p>
<p id="internet_lastvalue"></p>
<script>
    $(document).ready(function () {
        // 求和 a + b
        $("#sum1").click(function () {
            var a = $("#a1").val();
            var b = $("#b1").val();

            $.get("/trigger/add1/", {'a1': a, 'b1': b}, function (s) {
                $('#result1').html(s);
            });
        });
        // 列表 list
        $('#list').click(function () {
            $.getJSON('/trigger/ajax_list/', function (ret) {
                //返回值 ret 在这里是一个列表
                console.log(ret);
                for (var i = ret.length - 1; i >= 0; i--) {
                    // 把 ret 的每一项显示在网页上
                    $('#list_result').append(' ' + ret[i])
                }
            })
        });
        // 字典 dict
        $('#dict').click(function () {
            $.getJSON('/trigger/ajax_dict/', function (ret) {
                //返回值 ret 在这里是一个字典
                // for (var i = ret.length - 1; i >= 0; i--) {
                for (var i = 0; i < ret.length; i++) {
                    $('#dict_result').append(ret[i].twz + '<br>')
                }
                // 也可以用 ret['twz']
            })
        });
        //字典
        //$('#internet').click(function () {

    });
    //setInterval('internet()',3000)
</script>
<script type="text/javascript">
    function internet() {
        $.getJSON('/trigger/internet_lastvalue/', function (ret) {
            console.log(ret);
            var res = {
                name: [],
                invalue: [],
                outvalue: [],
                num: 0
            };
            var List = ret;
            var len = List.length;
            res.num = len;
            for (var i = 0; i < len; i++) {
                res.name.push(List[i]['company']);
                res.invalue.push(List[i]['invalue']);
                res.outvalue.push(List[i]['outvalue']);
                $('#internet_lastvalue').append(res.name.pop()+'<br>');
            }
            console.log(res);

            // 也可以用 ret['twz']
        })
    }
    //setInterval('internet()', 3000)
</script>
<script>
    $(document).ready(function () {
        $("#btn1").click(function () {
            $('#test').load('/static/ajax/out1.txt');
        })
    })
</script>

<script>
    function ajax_request() {
        var xmlhttp;
        if (window.XMLHttpRequest) {
            // code for IE7+, Firefox, Chrome, Opera, Safari
            xmlhttp = new XMLHttpRequest();
        } else {
            // code for IE6, IE5
            xmlhttp = new ActiveXObject("Microsoft.XMLHTTP");
        }
        console.log(xmlhttp.responseText);

        xmlhttp.onreadystatechange = function () {
            if (xmlhttp.readyState == 4 && xmlhttp.status == 200) {
                document.getElementById("result").innerHTML = xmlhttp.responseText;
            }
        };

        var a = document.getElementById("a").value;
        var b = document.getElementById("b").value;
        xmlhttp.open("GET", "/trigger/add/" + a + "/" + b + "/", true);
        xmlhttp.setRequestHeader("X-Requested-With", "XMLHttpRequest");
        xmlhttp.send();
        // ajax 教程：http://www.ziqiangxuetang.com/ajax/ajax-tutorial.html
    }
</script>
</body>
</html>

triggers/templates/triggers/backup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
ok!
</body>
</html>

triggers/templates/triggers/compare.html
{% extends "triggers/bootstrap.html" %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-5">
                <h3 class="page-header">对比完成！</h3>
            </div>
        </div>
    </div>
    <div class="container">
        <table class="table table-bordered table-hover table-responsive table-striped">
            <thead>
            <tr class="active">
                <th>文件名</th>
                <th>原文件</th>
                <th>新文件</th>
            </tr>
            </thead>
            {% for r in result %}
                {% if r.status != 0 %}
                    <tbody>
                    <tr>
                        <td>{{ r.file }}</td>
                        <td>
                            {% for f1 in r.str_old %}
                                {{ f1 }}<br>
                            {% endfor %}
                        </td>
                        <td>
                            {% for f2 in r.str_new %}
                                {{ f2 }}<br>
                            {% endfor %}
                        </td>
                    </tr>
                    </tbody>
                {% else %}
                    <tbody>
                    <tr>
                        <td>{{ r.file }}</td>
                        <td>正常</td>
                        <td>正常</td>
                    </tr>
                    </tbody>
                {% endif %}
            {% endfor %}
        </table>


        <a class="pure-button" href="{% url 'triggers:index' %}">返回首页</a>
    </div>
{% endblock %}

triggers/templates/triggers/history.html
{% extends "triggers/base.html" %}
{% block content %}
<div class="posts">
        <section class="post">
            {% if h_data %}
            <header class="post-header">
                <h3 class="post-title"><<{{ item_description }}>>5分钟内的流量如下：</h3>
            </header>
            <table class="pure-table" width="800" border="0">
                        <tr>
                            <th>流入速度</th>
                            <th>流出速度</th>
                            <th>时间</th>
                        </tr>
                         {% for h in h_data  %}
                        <tr>
                            <td align="center">{{ h.h_data_in }}</td>
                            <td align="center">{{ h.h_data_out }}</td>
                            <td align="center">{{ h.h_clock }}</td>
                        </tr>
                        {% endfor %}
            </table>
            {% else %}
                <header class="post-header">
                     <h3 class="post-title"><<{{ item_description }}>>历史数据不存在！</h3>
                 </header>
            {% endif %}
        </section>
        <a class="pure-button" href="{% url 'triggers:item_value' %}">线路流量</a> <a class="pure-button" href="{% url 'triggers:index' %}">返回首页</a>
</div><!-- /.blog-post -->
{% endblock %}

triggers/templates/triggers/home.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>欢迎光临 自强学堂！</title>
<script src="http://apps.bdimg.com/libs/jquery/1.10.2/jquery.min.js"></script>
</head>
<body>
<div id="list"> 学习 </div>
<div id='dict'></div>
<script type="text/javascript">
    // alert("涂伟忠提示您：注意页面上内容的变化。");

    //列表
    //var List = {{ List|safe }};
    //document.write(List[0]);
    function list_data() {
        var res = [];
        var List = {{ List|safe }};
        var len = List.length;
        //document.write(List.length);
        while (len--) {
            //document.write(List[len]);
            res.push(List[len])
        }
        return res;
    }
    document.write(list_data());
    //下面的代码把List的每一部分放到头部和尾部
    //$('#list').prepend(List[0]);
   // $('#list').append(List[1]);

    //console.log('--- 遍历 List 方法 1 ---')
    //for(i in List){
    //    document.write(List[i]);
    //}

    //console.log('--- 遍历 List 方法 2 ---')
    //for (var i = List.length - 1; i >= 0; i--) {
    //for (var i = 0; i++; i < List.length) {
        // 鼠标右键，审核元素，选择 console可以看到输入的值
        //document.write(i);
        //document.write(List[i]);
    //}
    var List = {{ List|safe }};
    console.log('--- 同时遍历索引和内容，使用 jQuery.each() 方法 ---')
    $.each(List, function(index, item){
        console.log(index);
        console.log(item);
    });


    // 字典
    var Dict = {{ Dict|safe }};
    console.log("--- 两种字典的取值方式  ---")
    console.log(Dict['site']);
    console.log(Dict.author);

    console.log("---  遍历字典  ---");
    for(i in Dict) {
        console.log(i + Dict[i]);//注意，此处 i 为键值
    }
</script>
</body>
</html>

triggers/templates/triggers/host.html
<!DOCTYPE html>
<html lang="zh-CN">
{% load staticfiles %}
{% load pagination_tags %}
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
<div class="container">
    <h4>《{{ servername }}》设备列表</h4>
</div>
<div class="container">
    <form class="form-inline" action="." method="GET">
        <div class="form-group">
            <label class="sr-only" for="q_hostname">路由器</label>
            <div class="input-group">
                <div class="input-group-addon">设备名称：</div>
                <input class="form-control" type="text" name="q_hostname"
                       value="{% if q_hostname %} {{ q_hostname }}{% endif %}">
            </div>
            <div class="input-group">
                <div class="input-group-addon">IP地址：</div>
                <input class="form-control" type="text" name="q_ip" value="{% if q_ip %} {{ q_ip }}{% endif %}">
            </div>
            <button class="btn btn-default" type="submit">查询</button>
        </div>
    </form>
</div>
<div class="container">
    <table class="table table-bordered table-hover table-responsive table-striped">
        <thead>
        <tr class="active">
            <th>设备ID</th>
            <th>设备名称</th>
            <th>设备IP地址</th>
            <th>设备状态</th>
        </tr>
        </thead>
        <tbody>
        {% autopaginate host_list 10 %}
        {% for h in host_list %}
            <tr>
                <td>{{ h.hostid }}</td>
                <td>{{ h.hostname }}</td>
                <td>{{ h.hostip }}</td>
                {% if h.status == 0 %}
                    <td>正常</td>
                {% else %}
                    <td>{{ h.status }}</td>
                {% endif %}
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% paginate %}
</div>
</body>

triggers/templates/triggers/host_init.html
{% extends "triggers/base.html" %}

{% block content %}
<div class="posts">
        <section class="post">
            <header class="post-header">
                <h1 class="post-title">监控设备同步完成！</h1>
            </header>
        </section>
        <a class="pure-button" href="{% url 'triggers:index' %}">返回首页</a>
</div><!-- /.blog-post -->
{% endblock %}

triggers/templates/triggers/video.html
{% extends "triggers/bootstrap.html" %}
{% load pagination_tags %}
{% block content %}
<div class="container">
   <div class="row">
      <div class="col-lg-5">
        <h3 class="page-header">集团视频会议状态列表</h3>
      </div>
   </div>
</div>
<div class="container">
                     {% if v_num.active != 0 %}
                     <p class="lead">
                         <h class="text-danger"> 当前有<b>{{ v_num.active }}</b>方正在召开视频会议：</h>
                     </p>
                     <table class="table table-bordered table-hover table-responsive table-striped">
                                <thead>
                                     <tr class="active">
                                         <th>公司</th>
                                         <th>会议室</th>
                                         <th>视频终端IP</th>
                                         <th>会议状态</th>
                                     </tr>
                                </thead>
                                <tbody>
                                     {% for t in v_meeting %}
                                     <tr class="alert-danger">
                                         <td align="center">{{ t.company }}</td>
                                         <td align="center">{{ t.hostname }}</td>
                                         <td align="center">{{ t.hostip }}</td>
                                         <td align="center">{{ t.description|cut:"{HOST.NAME}"|cut:"-" }}</td>
                                     </tr>
                                     {% endfor %}
                                </tbody>
                            </table>
                     {% endif %}
</div>
<div class="container">
    <p class="lead">
      <h4>详细视频会议终端列表，共有<b>{{ v_num.total }}</b>方，其中<b>{{ v_num.active }}</b>方正在召开视频会议：</h4>
    </p>
    <table class="table table-bordered table-hover table-responsive table-striped">
                       <thead>
                            <tr class="active">
                                <th>公司</th>
                                <th>会议室</th>
                                <th>视频终端IP</th>
                                <th>会议状态</th>
                                <th>上次会议结束时间</th>
                             </tr>
                       </thead>
                        <tbody>
                            {% autopaginate v_host 10 %}
                            {% for t in v_host %}
                                    <tr>
                                        <td align="center">{{ t.company }}</td>
                                        <td align="center">{{ t.hostname }}</td>
                                        <td align="center">{{ t.hostip }}</td>
                                        <td align="center">{{ t.description|cut:"{HOST.NAME}"|cut:"-" }}</td>
                                        <td align="center">{{ t.lastchange }}</td>
                                    </tr>
                            {% endfor %}
                        </tbody>
    </table>
     {% paginate %}
</div>
<div class="container" align="right">
      <a class="btn btn-default" href="{% url 'triggers:index' %}">返回首页</a>
</div>
{% endblock %}

triggers/templates/triggers/zhuanxian.html
{% extends "triggers/bootstrap.html" %}
{% load pagination_tags %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-5">
                <h3 class="page-header">集团专线状态列表</h3>
            </div>
        </div>
    </div>
    <div class="container">
        <p class="lead">
            <h class="text-danger">当前有<b>{{ z_num.problem_num }}</b>条发生故障：</h>
        </p>
        {% if z_num.problem_num != 0 %}
            <table class="table table-bordered table-hover table-responsive table-striped">
                <thead>
                <tr class="active">
                    <th>专线名称</th>
                    <th>专线IP</th>
                    <th>专线状态</th>
                    <th>故障时间</th>
                </tr>
                </thead>
                <tbody>
                {% for t in z_problem %}
                    <tr class="alert-danger">
                        <td><a class="post-author"
                               href="{% url 'triggers:zhuanxian_detail' t.hostip %}">{{ t.hostname }}</a></td>
                        <td>{{ t.hostip }}</td>
                        <td>{{ t.description|cut:"{HOST.NAME}"|cut:"-" }}</td>
                        <td>{{ t.lastchange }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        {% endif %}

        <p class="lead">详细专线列表，共有{{ z_num.total }}条，其中故障{{ z_num.problem_num }}条：</p>
        <table class="table table-bordered table-hover table-responsive table-striped">
            <thead>
            <tr>
                <th>专线名称</th>
                <th>专线IP</th>
                <th>专线状态</th>
            </tr>
            </thead>
            <tbody>
            {% autopaginate z_host 10 %}
            {% for t in z_host %}
                <tr class="pure-table pure-table-striped">
                    <td><a class="post-author"
                           href="{% url 'triggers:zhuanxian_detail' t.hostip %}">{{ t.hostname }}</a></td>
                    <td>{{ t.hostip }}</td>
                    <td>{{ t.description|cut:"{HOST.NAME}"|cut:"-" }}</td>
                </tr>
            {% endfor %}

            </tbody>
        </table>
        {% paginate %}
    </div>

    <div class="container" align="right">
        <a class="btn btn-default" href="{% url 'triggers:index' %}">返回首页</a>
    </div>
{% endblock %}